@InfoManager.Api_HostAddress = https://localhost:7217


@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5Y2RhMDIzNi1kY2YxLTRkNmYtYjdkZC1kOGVlOWIxNTQ4NzgiLCJlbWFpbCI6ImRhbnRoQGdtYWlsLmNvbSIsImp0aSI6ImZkYmMzYTM1LWZiZjMtNDgyZi1hNzI0LTYzYmY1ODQ2MjNkMiIsInJvbGUiOiJmYW1pbHlhZG1pbiIsIm5iZiI6MTc4NjY4NjEzOCwiZXhwIjoxNzg2Njg3MDM4LCJpYXQiOjE3ODY2ODYxMzh9.yowp2gVe1n0T0tn5NZA2VY4s5PINaQkB6UU5z1CwpSg

###

POST {{InfoManager.Api_HostAddress}}/api/Identities/register
Content-Type: application/json
{
  "Email": "dtchinhkhtn@yahoo.com",
  "Password": "P@ssw0rd"
}

###

POST {{InfoManager.Api_HostAddress}}/api/Identities/login
Content-Type: application/json
{
     "email":"danth@gmail.com",
   "password": "P@ssw0rd"
}

###

@id=e5c2537c-d8fe-4237-ae34-6ee948ec98e8
GET {{InfoManager.Api_HostAddress}}/api/Identities/user-detail/{{id}}
Authorization: Bearer {{token}}
###

@email=dtchinh
GET {{InfoManager.Api_HostAddress}}/api/Identities/users/search/{{email}}
Authorization: Bearer {{token}}

###
//Test update category success
PUT {{InfoManager.Api_HostAddress}}/api/Categories/6e6f59f5-7f5a-496d-9dd9-e8582c86f30b
Authorization: Bearer {{token}}
Content-Type: application/json
 {
    "id": "6e6f59f5-7f5a-496d-9dd9-e8582c86f30b",
    "name": "Bán hàng",
    "group": null,
    "keyName": "sale"
 }
###

GET {{InfoManager.Api_HostAddress}}/api/FamilyMembers?PageNumber=1&PageSize=20
Authorization: Bearer {{token}}
###

GET {{InfoManager.Api_HostAddress}}/api/FamilyMembers/7e627112-96bb-4f03-803f-0fc14bbbdbc6
Authorization: Bearer {{token}}
###
