//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoManager.Helper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoManager.Helper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} đã tồn tại !.
        /// </summary>
        internal static string ErrorAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Lỗi nghiệp vụ.
        /// </summary>
        internal static string ErrorBusinessRule {
            get {
                return ResourceManager.GetString("ErrorBusinessRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, không thể {0} {1} này !.
        /// </summary>
        internal static string ErrorCanNotAction {
            get {
                return ResourceManager.GetString("ErrorCanNotAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, không thể xóa !.
        /// </summary>
        internal static string ErrorCannotDelete {
            get {
                return ResourceManager.GetString("ErrorCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, không thể xóa lí do : {0} !.
        /// </summary>
        internal static string ErrorCannotDeleteWithReason {
            get {
                return ResourceManager.GetString("ErrorCannotDeleteWithReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Không thể lấy dữ liệu của {0} !.
        /// </summary>
        internal static string ErrorCannotRetrieveData {
            get {
                return ResourceManager.GetString("ErrorCannotRetrieveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, xung đột dữ liệu !.
        /// </summary>
        internal static string ErrorConflict {
            get {
                return ResourceManager.GetString("ErrorConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, xung đột dữ liệu. Chi tiết: {0}.
        /// </summary>
        internal static string ErrorConflictWithDetails {
            get {
                return ResourceManager.GetString("ErrorConflictWithDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} !.
        /// </summary>
        internal static string ErrorCustom {
            get {
                return ResourceManager.GetString("ErrorCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, bị cấm sử dụng !.
        /// </summary>
        internal static string ErrorForbidden {
            get {
                return ResourceManager.GetString("ErrorForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} không hợp lệ !.
        /// </summary>
        internal static string ErrorInvalid {
            get {
                return ResourceManager.GetString("ErrorInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} không thể vượt quá {1} ký tự !.
        /// </summary>
        internal static string ErrorMaxLength {
            get {
                return ResourceManager.GetString("ErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} tối đa là {1} !.
        /// </summary>
        internal static string ErrorMaxValue {
            get {
                return ResourceManager.GetString("ErrorMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} phải lớn hơn hoặc bằng {1} !.
        /// </summary>
        internal static string ErrorMinValue {
            get {
                return ResourceManager.GetString("ErrorMinValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0}  sai dữ liệu (hoặc không khớp) !.
        /// </summary>
        internal static string ErrorMismatch {
            get {
                return ResourceManager.GetString("ErrorMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} không được trống !.
        /// </summary>
        internal static string ErrorNotEmpty {
            get {
                return ResourceManager.GetString("ErrorNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} không tồn tại !.
        /// </summary>
        internal static string ErrorNotExists {
            get {
                return ResourceManager.GetString("ErrorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, không tìm thấy {0} nào !.
        /// </summary>
        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, không tìm thấy {0} có Id = {1}.
        /// </summary>
        internal static string ErrorNotFoundWithId {
            get {
                return ResourceManager.GetString("ErrorNotFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} vô giá trị!.
        /// </summary>
        internal static string ErrorNull {
            get {
                return ResourceManager.GetString("ErrorNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} phải nằm trong đoạn [{1} - {2}] !.
        /// </summary>
        internal static string ErrorOutOfRange {
            get {
                return ResourceManager.GetString("ErrorOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, {0} là bắt buộc !.
        /// </summary>
        internal static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, lỗi hệ thống !.
        /// </summary>
        internal static string ErrorServer {
            get {
                return ResourceManager.GetString("ErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, không xác thực !.
        /// </summary>
        internal static string ErrorUnauthorized {
            get {
                return ResourceManager.GetString("ErrorUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Xảy ra lỗi không xác định !.
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info, Không có thay đổi nào !.
        /// </summary>
        internal static string InfoNoChanges {
            get {
                return ResourceManager.GetString("InfoNoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success, {0} đã được {1} thành công !.
        /// </summary>
        internal static string SuccessAction {
            get {
                return ResourceManager.GetString("SuccessAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success, {0} !.
        /// </summary>
        internal static string SuccessCustom {
            get {
                return ResourceManager.GetString("SuccessCustom", resourceCulture);
            }
        }
    }
}
